In [15]:
import numpy as np
from os import getcwd
from scipy import stats

In [4]:
file = r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_01_01_nava_10\001_TrendRRInspTimeETCO2_0000.nta"

In [5]:
c = np.loadtxt(file, comments="%", usecols=(3, 4, 6))

In [6]:
np.shape(c)

(170, 3)

In [16]:
# LOAD SERVO
servopath = r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_01_01_nava_10\001_ServoCurveData_0000.nta"
servodata = np.loadtxt(servopath, comments="%", usecols=(3, 4, 5, 6))
np.shape(servodata)

DescribeResult(nobs=30466, minmax=(array([     0.,    223., -13617.,      0.]), array([1.0000e+00, 2.3780e+03, 1.3273e+04, 1.5740e+03])), mean=array([4.32285170e-01, 7.84155354e+02, 1.25558491e+02, 3.64932318e+02]), variance=array([2.45422757e-01, 1.40232118e+05, 3.84745875e+07, 1.14702856e+05]), skewness=array([0.27337796, 1.63510751, 0.41801757, 0.98792001]), kurtosis=array([-1.92526449,  1.82364143, -1.32082921,  0.03870115]))

In [25]:
# LOAD VOLUME
volumepath = r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_01_01_nava_10\001_TrendTidalVolumeNIVLeakage_0000.nta"
volumedata = np.round((np.loadtxt(volumepath, comments="%", usecols=(3, 4)) / 10000000), 3)
np.shape(volumedata)
volumedata


array([[0.   , 0.612],
       [0.   , 0.633],
       [0.   , 0.59 ],
       [0.   , 0.668],
       [0.   , 0.688],
       [0.   , 0.631],
       [0.   , 0.659],
       [0.   , 0.643],
       [0.   , 0.639],
       [0.   , 0.651],
       [0.   , 0.606],
       [0.   , 0.6  ],
       [0.   , 0.623],
       [0.   , 0.607],
       [0.   , 0.604],
       [0.   , 0.605],
       [0.   , 0.621],
       [0.   , 0.58 ],
       [0.   , 0.319],
       [0.   , 0.717],
       [0.   , 0.557],
       [0.   , 0.723],
       [0.   , 0.628],
       [0.   , 0.601],
       [0.   , 0.593],
       [0.   , 0.658],
       [0.   , 0.654],
       [0.   , 0.627],
       [0.   , 0.562],
       [0.   , 0.626],
       [0.   , 0.639],
       [0.   , 0.649],
       [0.   , 0.567],
       [0.   , 0.666],
       [0.   , 0.586],
       [0.   , 0.456],
       [0.   , 0.615],
       [0.   , 0.571],
       [0.   , 0.486],
       [0.   , 0.577],
       [0.   , 0.598],
       [0.   , 0.651],
       [0.   , 0.526],
       [0. 

In [10]:
# LOAD RR
rrpath = r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_01_01_nava_10\001_TrendRRInspTimeETCO2_0000.nta"
rrdata = np.loadtxt(rrpath, comments="%", usecols=(3, 4, 6))
np.shape(rrdata)

(170, 3)

In [40]:
# LOAD BREATH
breathpath = r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_new\Breath_00000000.sta"
breathdata = np.loadtxt(breathpath, comments="%", usecols=(1, 2, 3))
np.shape(breathdata)
breathdata

array([[  19. ,   42.4,   56.8],
       [ 184. ,   41.9,   54.6],
       [ 327. ,   42.1,   62.8],
       [ 510. ,   41.3,   61.4],
       [ 593. ,   42.2,   39.8],
       [ 717. ,   42.7,   37.4],
       [ 880. ,   42.8,   54.8],
       [1023. ,   43.2,   48.6],
       [1125. ,   42.9,   37.4],
       [1228. ,   43.3,   39.2],
       [1393. ,   43.4,   60.4],
       [1517. ,   44. ,   43.4],
       [1701. ,   43.5,   43.8],
       [1864. ,   43.9,   45.2],
       [1968. ,   44.5,   19.2],
       [2030. ,   43.7,   37. ],
       [2233. ,   43.3,   49.2],
       [2376. ,   43.7,   50.2],
       [2519. ,   43.6,   53. ],
       [2682. ,   43.3,   48.6],
       [2865. ,   43.9,   40.6],
       [3028. ,   43.2,   59.8],
       [3171. ,   43.9,   51.2]])

In [13]:
# LOAD CURVES
curvespaths = [r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_new\Curves_00000000.sta",
              r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_new\Curves_00000001.sta",
              r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_new\Curves_00000002.sta",
              r"C:\Users\Emanuele Lovera\Documents\Python\PIClassifier\data\p_new\Curves_00000003.sta"]
curvesdata = None
for file_path in curvespaths:
    if curvesdata is None:
        curvesdata = np.loadtxt(file_path, comments="%", usecols=(2, 3, 5, 6))
    else:
        curvesdata = np.concatenate((curvesdata, np.loadtxt(file_path, comments="%", usecols=(2, 3, 5, 6))))
np.shape(curvesdata)

(3253, 4)

In [36]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a[:,1] / 2

array([1. , 2.5])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])