In [5]:
import numpy as np
from os import getcwd
from scipy import stats

In [7]:
# LOAD SERVO
servopath = "./data/p_01_01_nava_10/001_ServoCurveData_0000.nta"
servodata = np.loadtxt(servopath, comments="%", usecols=(3, 4, 5, 6))
np.shape(servodata)

(30466, 4)

In [9]:
# LOAD VOLUME
volumepath = "./data/p_01_01_nava_10/001_TrendTidalVolumeNIVLeakage_0000.nta"
volumedata = np.round((np.loadtxt(volumepath, comments="%", usecols=(3, 4)) / 10000000), 3)
np.shape(volumedata)

(170, 2)

In [10]:
# LOAD RR
rrpath = "./data/p_01_01_nava_10/001_TrendRRInspTimeETCO2_0000.nta"
rrdata = np.loadtxt(rrpath, comments="%", usecols=(3, 4, 6))
np.shape(rrdata)

(170, 3)

In [12]:
# LOAD BREATH
breathpath = "./data/p_new/Breath_00000000.sta"
breathdata = np.loadtxt(breathpath, comments="%", usecols=(1, 2, 3))
np.shape(breathdata)

(23, 3)

In [13]:
# LOAD CURVES
curvespaths = ["./data/p_new/Curves_00000000.sta",
              "./data/p_new/Curves_00000001.sta",
              "./data/p_new/Curves_00000002.sta",
              "./data/p_new/Curves_00000003.sta"]
curvesdata = None
for file_path in curvespaths:
    if curvesdata is None:
        curvesdata = np.loadtxt(file_path, comments="%", usecols=(2, 3, 5, 6))
    else:
        curvesdata = np.concatenate((curvesdata, np.loadtxt(file_path, comments="%", usecols=(2, 3, 5, 6))))
np.shape(curvesdata)

(3253, 4)

In [36]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a[:,1] / 2

array([1. , 2.5])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
range(23)

range(0, 23)

In [15]:
for i in range(23):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [16]:
line = [0] * 4
line

[0, 0, 0, 0]